### ISSUE TITLE
Virus warning?

### ISSUE THREAD

**Issue by harryray33** [aloneguid/clipnest#2]
I downloaded v1.13 and got a virus warning from ESET, I tried downloading via Softpedia (from the Softpedia server) and didn't get the warning.

Any idea why?

Thanks.

**Comment by aloneguid** [comment]
From what I can see almost all open source software is marked as a virus mostly because it's not digitally signed. Certificates are expensive so it won't happen anytime soon unless I get enough donations here, but let's be honest) This application is fully open with no hidden code so if you don't believe it's not a virus feel free t browse source code.

BR. Ivan.
________________________________
From: harryray33 ***@***.***>
Sent: Thursday, November 3, 2022 7:25:09 PM
To: aloneguid/clipnest ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aloneguid/clipnest] Virus warning? (Issue #2)


I downloaded v1.13 and got a virus warning from ESET, I tried downloading via Softpedia (from the Softpedia server) and didn't get the warning.

Any idea why?

Thanks.

**Comment by harryray33** [comment]
Thanks, why I was curious was because it's only 1.13 that's flagged,

**Comment by aloneguid** [comment]
I had to in fact remove functionality to watch clipboard for changes as Windows Defender was flagging it as malicious. So now it only triggers calculation when you click on the tray icon. Other than that there's nothing dangerous going on ;)
